# Generated by Django 4.1 on 2023-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('option', models.IntegerField(choices=[(1, 'Happy'), (2, 'Relaxing'), (3, 'Sad'), (4, 'Energetic')])),
            ],
        ),
    ]
