# Generated by Django 4.1 on 2023-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='filepath',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='media',
            field=models.BinaryField(null=True),
        ),
    ]
