# Generated by Django 4.1 on 2023-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRec', '0002_songs_filepath_songs_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='media',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
